#!/usr/bin/env bash

################
# list         #
################

colorflag="--color"

# List all files colorized in long format
alias l="ls -lhF ${colorflag}"
alias ll="ls -lhF ${colorflag}"

# List all files colorized in long format, including dot files
alias la="ls -lahF ${colorflag}"

# List only directories
alias lsd="ls -lhF ${colorflag} | grep --color=never '^d'"

# Always use color output for `ls`
alias ls="command ls ${colorflag}"

################
# !list        #
################

# Easier navigation: .., ..., ...., ~
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# Always enable colored `grep` output
alias grep='grep --color=auto '

# Shortcuts
alias bk="cd -"
alias c="cd"
alias cl="clear"
alias cc="cat"
alias fd="find . -name"
alias h="history | tail -40"
alias n="/usr/local/bin/nvim"
alias rm="safe-rm"
alias sr="source ${HOME}/.bashrc"
alias v="vim"

# untar
alias untar="tar xvf"

# Workspace
alias p="cd ${HOME}/jdk/jdk-src-dev"
alias mydot="cd ${HOME}/hsun-code.code/dotfiles"
alias myhome="cd ${HOME}/myhome"
alias mynv="cd ${HOME}/hsun-code.code/NvChad"

if [ $(nproc) -gt 4 ] ; then njobs=$(($(nproc) / 2)) ; else njobs=1 ; fi
alias jdk-reconf-build="make reconfigure;make clean;make images JOBS=${njobs}"
alias jdk-build="make images JOBS=${njobs}"

# alias login-a64fx2="bash ${HOME}/myhome/scripts/login-a64fx2.sh"
# alias login-a64fx3="bash ${HOME}/myhome/scripts/login-a64fx3.sh"

