#!/usr/bin/env bash

################
# list         #
################

colorflag="--color"

# List all files colorized in long format
alias l="ls -lhF ${colorflag}"
alias ll="ls -lhF ${colorflag}"

# List all files colorized in long format, including dot files
alias la="ls -lahF ${colorflag}"

# List only directories
alias lsd="ls -lhF ${colorflag} | grep --color=never '^d'"

# Always use color output for `ls`
alias ls="command ls ${colorflag}"

################
# !list        #
################

# Easier navigation: .., ..., ...., ~
alias ..="cd ..; ls"
alias ...="cd ../..; ls"
alias ....="cd ../../..; ls"

# Always enable colored `grep` output
alias grep='grep --color=auto '

# Shortcuts
alias h="history | tail -40"
alias n="/usr/local/bin/nvim"
alias sr="source ${HOME}/.bashrc"
alias v="vim"

# untar
alias untar="tar xvf"

# dcoker
alias da="docker ps -a"

# git
alias git-set-loc="git config --local user.name 'Hao Sun';git config --local user.email 'hsun-code@outlook.com'"

# Workspace
alias p="cd ${HOME}/jdk/jdk-src-dev; l"
alias myc="cd ${HOME}/ci-scripts-dev; l"
alias mydot="cd ${HSUN_DOTS}; l"
alias myhome="cd ${HSUN_HOME}; l"
alias mynv="cd ${HSUN_NVIM}; l"
alias hsun_bootstrap="bash ${HSUN_HOME}/scripts/setup/bootstrap.sh"

if [ $(hsun_ncpu) -gt 32 ] ; then njobs=$(($(hsun_ncpu) / 2)) ; else njobs=$(hsun_ncpu) ; fi
hsun_echo "njobs is $njobs"
alias jdk-reconf-build="make reconfigure;make clean;make images JOBS=${njobs};make test-image"
alias jdk-build="make images JOBS=${njobs};make test-image"
alias jdk-conf="bash ../jdk-src-dev/configure --with-boot-jdk=${HSUN_LIBS}/boot-jdk-aarch64 \
                --with-jtreg=${HSUN_LIBS}/jtreg --with-gtest=${HSUN_LIBS}/gtest \
                --disable-precompiled-headers --with-debug-level=fastdebug $@"

