#!/bin/bash

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";

# Do not clear the screen after quitting a manual page
export MANPAGER="less -X";

# Workspace: hsdis and jtreg
MY_LIB_PATH="$HOME/libs"
if [[ "$LD_LIBRARY_PATH" != *"$MY_LIB_PATH:"* ]]; then
  export LD_LIBRARY_PATH="$MY_LIB_PATH:$LD_LIBRARY_PATH"
fi
echo "LD_LIBRARY_PATH:$LD_LIBRARY_PATH"

